include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - "/*.g.dart"
    - "*.g.dart"
    - "/*.gen.dart"
    - "lib/locale_keys.g.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    constant_identifier_names: false